name: sample-python

services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: timonweb-forks/sample-python
  name: sample-python
  routes:
  - path: /

- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: timonweb-forks/sample-python
  name: sample-python-us
  routes:
  - path: /us
